server:
  port: 9090

spring:
  application:
    name: service
  config:
    import: optional:configserver:http://localhost:8888/config
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect


