server:
  port: 9090



spring:
  application:
    name: service
  config:
    import: optional:configserver:http://localhost:8888/config
  datasource:
    url: jdbc:postgresql://localhost:5432/testdatadb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true



